export {default as Discord} from './discord'
export {default as GitHub} from './github'
export {default as Instagram} from './instagram'
export {default as LinkedIn} from './linkedin'
export {default as Spotify1} from './spotify1'
export {default as Spotify2} from './spotify2'
export {default as XIcon} from './xicon'
